# Generated by Django 4.1.2 on 2022-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subit', models.URLField(max_length=50)),
                ('subit1', models.FileField(upload_to='')),
            ],
        ),
    ]
