# Generated by Django 4.1.2 on 2022-10-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participants_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
