# Generated by Django 4.1.2 on 2022-10-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_participants_roll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participants',
            new_name='Participant',
        ),
    ]
