# Generated by Django 4.1.2 on 2022-10-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_participants_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='subit',
            field=models.URLField(),
        ),
    ]
